### ISSUE TITLE
an error occurs while uploading the resume 

### ISSUE THREAD

**Issue by Atharva12072004** [kazcfz/Alumni-Portal#1]

**Comment by kazcfz** [comment]
What's the error you're seeing when attempting to upload a resume to a profile? Do also share the log messages from the browser's console.

Example:
![image](https://github.com/user-attachments/assets/6dc7c3ba-7b7a-4266-95d4-6bf65b02f496)

**Comment by kazcfz** [comment]
Can't repro so closing this for now
